# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro humble
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-gtest, ament-lint-auto, ament-lint-common, builtin-interfaces, micro-ros-msgs, rcutils, rmw, rmw-dds-common, rmw-fastrtps-shared-cpp, rosidl-default-generators, rosidl-typesupport-fastrtps-cpp }:
buildRosPackage rec {
  pname = "ros-humble-micro-ros-agent";
  version = "3.0.6";

  src = fetchFromGitHub {
    owner = "micro-ROS";
    repo = "micro-ROS-Agent";
    rev = "4f363a79ae96aed39dcc5269f53f73f6a70d3a2c";
    sha256 = "0pj5inpqwp4m7vs88mvca0n55am4lz1m2zaapfnapv90zh4zaw1q";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/micro_ros_agent/";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ament-lint-common builtin-interfaces rosidl-default-generators rosidl-typesupport-fastrtps-cpp ];
  propagatedBuildInputs = [ micro-ros-msgs rcutils rmw rmw-dds-common rmw-fastrtps-shared-cpp ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "micro-ROS Agent package";
    license = with lib.licenses; [ asl20 ];
  };
}
